// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn9dI4snNQTIl3OENwxSC-06y-gqsfP34',
    appId: '1:882100728991:web:22c1f9f18f70ebcc78deaa',
    messagingSenderId: '882100728991',
    projectId: 'strk-thebestone',
    authDomain: 'strk-thebestone.firebaseapp.com',
    storageBucket: 'strk-thebestone.firebasestorage.app',
    measurementId: 'G-W01PNXJ9B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4Tm9m3a1kF2SQ3k1hLu9H9fcBJh-36A',
    appId: '1:882100728991:android:35d4050e26720a7778deaa',
    messagingSenderId: '882100728991',
    projectId: 'strk-thebestone',
    storageBucket: 'strk-thebestone.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMIbBADpJQtojigUDKS9NOnInl4Z1XS8',
    appId: '1:882100728991:ios:3c8cf39611fc07de78deaa',
    messagingSenderId: '882100728991',
    projectId: 'strk-thebestone',
    storageBucket: 'strk-thebestone.firebasestorage.app',
    iosClientId: '882100728991-k7m9cc27hpt6g0l670hamsk9dgq2qfbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMIbBADpJQtojigUDKS9NOnInl4Z1XS8',
    appId: '1:882100728991:ios:3c8cf39611fc07de78deaa',
    messagingSenderId: '882100728991',
    projectId: 'strk-thebestone',
    storageBucket: 'strk-thebestone.firebasestorage.app',
    iosClientId: '882100728991-k7m9cc27hpt6g0l670hamsk9dgq2qfbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn9dI4snNQTIl3OENwxSC-06y-gqsfP34',
    appId: '1:882100728991:web:a6ff9befc5c291ef78deaa',
    messagingSenderId: '882100728991',
    projectId: 'strk-thebestone',
    authDomain: 'strk-thebestone.firebaseapp.com',
    storageBucket: 'strk-thebestone.firebasestorage.app',
    measurementId: 'G-WRK37K721W',
  );
}
